name: SauceLabs Tests Remotely

on:
  workflow_dispatch:

jobs:
  Samsung_Ubuntu_Android_Test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="testCasesByW3cTouchActions.AddToCartTests#addProductToCartByDragAndDrop"
          -DappiumExecutionType="SauceLabs"
          -DAppiumServerURL="https://ondemand.eu-central-1.saucelabs.com:443/wd/hub"
          -DappType="NativeAndroid"
          -DdeviceName="Samsung Galaxy S23 FE"
          -DplatformVersion="14"
          -DnativeAutomationDriver="UiAutomator2"
          -DappName="Android-SauceLabs.apk"
          -Dusername="oauth-jmetwallym-40486"
          -DaccessKey="02b2f4ca-6237-456d-b725-aad1e104ae91"
          -DparallelMode="NONE"
          -DsyncWithDB="false"
          -DSwipeRate="200"

      - name: Generate Allure report
        run: mvn allure:report

      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report UI Tests Chrome Ubuntu
          path: "target/site/allure-maven-plugin"